/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.allan.siszorzo.interfaces;

import br.com.allan.siszorzo.classes.Cad_Estado_TO;
import br.com.allan.siszorzo.classes.Cad_Fornecedor_TO;
import br.com.allan.siszorzo.dao.Cad_Estado_DAO;
import br.com.allan.siszorzo.dao.Cad_Fornecedor_DAO;
import br.com.allan.siszorzo.grades.Tabela_Busca_Fornecedor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan
 */
public final class JIFCadastroFornecedor extends javax.swing.JInternalFrame {

    private Cad_Fornecedor_TO cad_fornecedor;
    Tabela_Busca_Fornecedor ga;

    public JIFCadastroFornecedor() throws Exception {
        initComponents();
        ga = new Tabela_Busca_Fornecedor();
        GradeBuscaFornecedor.setModel(ga);

//        BuscaCliente.setMaximumSize(null);//JFrame no meio da tela
//        BuscaCliente.setLocation(400, 207);//seta a localização da tela
        BuscaFornecedor.setMinimumSize(new Dimension(850, 500));//seta a dimensão/tamanho da tela
        BuscaFornecedor.setResizable(false);//desabilita a opção de maximizar
        BuscaFornecedor.setLocationRelativeTo(null);//Seta o Frame centralizado
        carregaCombo();
        dataHohe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscaFornecedor = new javax.swing.JFrame();
        JBBuscaFornecedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GradeBuscaFornecedor = new javax.swing.JTable();
        JLNomeRazao = new javax.swing.JLabel();
        JTFNomeRazao = new javax.swing.JTextField();
        JLCPFCNPJ = new javax.swing.JLabel();
        JTFCPFCNPJ = new javax.swing.JTextField();
        JBCNPJCPF = new javax.swing.JButton();
        JBIncricaoEstadual = new javax.swing.JLabel();
        JTFInscricaoEstadual = new javax.swing.JTextField();
        JLEMAIL = new javax.swing.JLabel();
        JLEndereco = new javax.swing.JLabel();
        JTFEndereco = new javax.swing.JTextField();
        JLBairroDistrito = new javax.swing.JLabel();
        JTFBairroDistrito = new javax.swing.JTextField();
        JLNumero = new javax.swing.JLabel();
        JTFNumero = new javax.swing.JTextField();
        JLCEP = new javax.swing.JLabel();
        JFTLCEP = new javax.swing.JFormattedTextField();
        JLEstado = new javax.swing.JLabel();
        JCBEstado = new javax.swing.JComboBox();
        JLCidade = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        JLDataCadastro = new javax.swing.JLabel();
        JLTelefone = new javax.swing.JLabel();
        JFTLTelefone = new javax.swing.JFormattedTextField();
        JLCelular1 = new javax.swing.JLabel();
        JFTLCelular1 = new javax.swing.JFormattedTextField();
        JLCelular2 = new javax.swing.JLabel();
        JFTLCelular2 = new javax.swing.JFormattedTextField();
        JLObservacao = new javax.swing.JLabel();
        JBGravar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAObervacao = new javax.swing.JEditorPane();
        JTFEmail = new javax.swing.JTextField();
        JDCDataCadastro = new com.toedter.calendar.JDateChooser();

        BuscaFornecedor.setTitle("Busca de Cliente");

        JBBuscaFornecedor.setText("Selecionar o Fornecedor Desejado");
        JBBuscaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscaFornecedorActionPerformed(evt);
            }
        });

        GradeBuscaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(GradeBuscaFornecedor);

        javax.swing.GroupLayout BuscaFornecedorLayout = new javax.swing.GroupLayout(BuscaFornecedor.getContentPane());
        BuscaFornecedor.getContentPane().setLayout(BuscaFornecedorLayout);
        BuscaFornecedorLayout.setHorizontalGroup(
            BuscaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscaFornecedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBBuscaFornecedor)))
                .addContainerGap())
        );
        BuscaFornecedorLayout.setVerticalGroup(
            BuscaFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaFornecedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBBuscaFornecedor)
                .addContainerGap())
        );

        setClosable(true);
        setTitle("Cadastro de Fornecedor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/allan/siszorzo/imagens/Fornecedor.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(728, 555));

        JLNomeRazao.setText("Nome/Razão:");

        JTFNomeRazao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFNomeRazaoKeyPressed(evt);
            }
        });

        JLCPFCNPJ.setText("CNPJ:");

        JBCNPJCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/allan/siszorzo/imagens/Busca.png"))); // NOI18N
        JBCNPJCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCNPJCPFActionPerformed(evt);
            }
        });

        JBIncricaoEstadual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBIncricaoEstadual.setText("Inscrição Estadual:");

        JLEMAIL.setText("E-mail:");

        JLEndereco.setText("Endereço:");

        JLBairroDistrito.setText("Bairro/Distrito:");

        JLNumero.setText("Número:");

        JLCEP.setText("CEP:");

        try {
            JFTLCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JLEstado.setText("Estado:");

        JLCidade.setText("Cidade:");

        JLDataCadastro.setText("Data do Cadastro:");

        JLTelefone.setText("Telefone:");

        try {
            JFTLTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JLCelular1.setText("Celular:");

        try {
            JFTLCelular1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JLCelular2.setText("Celular:");

        try {
            JFTLCelular2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JLObservacao.setText("Observação:");

        JBGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/allan/siszorzo/imagens/Salvar.png"))); // NOI18N
        JBGravar.setText("Gravar");
        JBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGravarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(JTAObervacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLBairroDistrito)
                                .addGap(6, 6, 6)
                                .addComponent(JTFBairroDistrito))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLObservacao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLTelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JFTLTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JLCelular1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JFTLCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JLCelular2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JFTLCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(JLCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLDataCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDCDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBGravar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLCPFCNPJ)
                            .addComponent(JLEndereco)
                            .addComponent(JLEMAIL))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTFCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBCNPJCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBIncricaoEstadual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFInscricaoEstadual))
                            .addComponent(JTFNomeRazao)
                            .addComponent(JTFEmail)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JTFEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLNumero)
                                    .addComponent(JLCEP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JFTLCEP)
                                    .addComponent(JTFNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGap(35, 35, 35)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLNomeRazao)
                            .addComponent(JTFNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JTFCPFCNPJ)
                                .addComponent(JLCPFCNPJ))
                            .addComponent(JBCNPJCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFInscricaoEstadual)
                            .addComponent(JBIncricaoEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLEMAIL)
                            .addComponent(JTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLEndereco)
                            .addComponent(JTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLNumero)
                            .addComponent(JTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLBairroDistrito)
                            .addComponent(JTFBairroDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLCEP)
                            .addComponent(JFTLCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLEstado)
                            .addComponent(JCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLCidade)
                            .addComponent(JLDataCadastro)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JDCDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLTelefone)
                    .addComponent(JFTLTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLCelular1)
                    .addComponent(JFTLCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLCelular2)
                    .addComponent(JFTLCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLObservacao)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBGravar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void carregaTabelaClientes() {
        try {
            List l = Cad_Fornecedor_DAO.getInstance().buscar(JTFNomeRazao.getText());  // passa a consulta feita pelo DAO            
            ga.setDados(l);
            GradeBuscaFornecedor.updateUI();
        } catch (Throwable t) {
            t.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao Buscar Cliente!");
        }
    }

    public void carregaCombo() throws Exception {
        JCBEstado.removeAllItems();//removendo tds os itens da combo
        JCBEstado.addItem(null);
        //fazendo uma busca no banco para trazer na combo e listando a classe na qual foi criado a janela anterior
        ArrayList<Cad_Estado_TO> l = Cad_Estado_DAO.getInstance().buscar(); //tem q ta = o nome da classe criada
        for (Cad_Estado_TO tipo : l) {
            JCBEstado.addItem(tipo);
        }
    }

    public void limparDados() {
        JCBEstado.setSelectedItem(null);
        jtfCidade.setText("");
        JTFInscricaoEstadual.setText("");
        JTFNomeRazao.setText("");
        JTFCPFCNPJ.setText("");
        JTFInscricaoEstadual.setText("");
        JTFEmail.setText("");
        JTFEndereco.setText("");
        JTFBairroDistrito.setText("");
        JTFNumero.setText("");
        JFTLCEP.setText("");
        jtfCidade.setText("");
        JDCDataCadastro.setDate(null);
        JFTLTelefone.setText("");
        JFTLCelular1.setText("");
        JFTLCelular2.setText("");
        JTAObervacao.setText("");
        JTFNomeRazao.requestFocus(true);
        dataHohe();
    }

    //traz a data do dia no campo data de cadastro
    public void dataHohe() {
        JDCDataCadastro.setDate(new java.util.Date());
    }
    private void JBCNPJCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCNPJCPFActionPerformed
        //Abrindo o site da receita para a consulta CNPJ quando clicado no botão de busca
        Desktop desktop = null;
        desktop = Desktop.getDesktop();
        URI uri = null;

        try {
            uri = new URI("http://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/cnpjreva_solicitacao.asp"); //NOI18N
            desktop.browse(uri);
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (URISyntaxException use) {
            //use.printStackTrace();
            System.out.println("Erro ao acessar URL."); //NOI18N
        }
    }//GEN-LAST:event_JBCNPJCPFActionPerformed

    private void JBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGravarActionPerformed
        //  Validacampos();
        try {
            if (cad_fornecedor == null) {
                Cad_Fornecedor_TO t = new Cad_Fornecedor_TO();//criando o objeto e grava nele
                t.setTxt_nomerazaosocial(JTFNomeRazao.getText());
                t.setNum_cpfcnpj(JTFCPFCNPJ.getText());
                t.setNum_inscricaoestatudal(JTFInscricaoEstadual.getText());
                t.setTxt_email(JTFEmail.getText());
                t.setTxt_endereco(JTFEndereco.getText());
                t.setTxt_bairrodistrito(JTFBairroDistrito.getText());
                t.setNum_numero(JTFNumero.getText());
                t.setNum_cep(JFTLCEP.getText());
                t.setCad_estado((Cad_Estado_TO) JCBEstado.getSelectedItem());
                t.setTxt_cidade(jtfCidade.getText());
                t.setDt_datacadastro(JDCDataCadastro.getDate());
                t.setNum_telefone(JFTLTelefone.getText());
                t.setNum_celular1(JFTLCelular1.getText());
                t.setNum_celular2(JFTLCelular2.getText());
                t.setTxt_observacao(JTAObervacao.getText());
                Cad_Fornecedor_DAO.incluir(t);//passando o objeto criado
                JOptionPane.showMessageDialog(this, "Cadastro realizado com Sucesso!");
            } else {
                cad_fornecedor.setTxt_nomerazaosocial(JTFNomeRazao.getText());
                cad_fornecedor.setNum_cpfcnpj(JTFCPFCNPJ.getText());
                cad_fornecedor.setNum_inscricaoestatudal(JTFInscricaoEstadual.getText());
                cad_fornecedor.setTxt_email(JTFEmail.getText());
                cad_fornecedor.setTxt_endereco(JTFEndereco.getText());
                cad_fornecedor.setTxt_bairrodistrito(JTFBairroDistrito.getText());
                cad_fornecedor.setNum_numero(JTFNumero.getText());
                cad_fornecedor.setNum_cep(JFTLCEP.getText());
                cad_fornecedor.setCad_estado((Cad_Estado_TO) JCBEstado.getSelectedItem());
                cad_fornecedor.setTxt_cidade(jtfCidade.getText());
                cad_fornecedor.setDt_datacadastro(JDCDataCadastro.getDate());
                cad_fornecedor.setNum_telefone(JFTLTelefone.getText());
                cad_fornecedor.setNum_celular1(JFTLCelular1.getText());
                cad_fornecedor.setNum_celular2(JFTLCelular2.getText());
                cad_fornecedor.setTxt_observacao(JTAObervacao.getText());
                Cad_Fornecedor_DAO.alterar(cad_fornecedor);//passando o objeto criado
                JOptionPane.showMessageDialog(this, "Cadastro alterado com Sucesso!");
            }
            carregaCombo();
            limparDados();
        } catch (Throwable t) {
            //msg quando existir duplicidade nas informações ja registradas
            JOptionPane.showMessageDialog(this, "Erro ao Cadastrar ou alterar os dados!");
            t.getMessage();
        }
    }//GEN-LAST:event_JBGravarActionPerformed

    private void JBBuscaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscaFornecedorActionPerformed
        try {
            //pegando a opção selecionada na grade
            cad_fornecedor = (Cad_Fornecedor_TO) ga.getDadoAt(GradeBuscaFornecedor.getSelectedRow());
            if (cad_fornecedor != null) {
                JTFNomeRazao.setText(cad_fornecedor.getTxt_nomerazaosocial());
                JTFCPFCNPJ.setText(cad_fornecedor.getNum_cpfcnpj());
                JTFInscricaoEstadual.setText(cad_fornecedor.getNum_inscricaoestatudal());
                JTFEmail.setText(cad_fornecedor.getTxt_email());
                JTFEndereco.setText(cad_fornecedor.getTxt_endereco());
                JTFBairroDistrito.setText(cad_fornecedor.getTxt_bairrodistrito());
                JTFNumero.setText(cad_fornecedor.getNum_numero());
                JFTLCEP.setText(cad_fornecedor.getNum_cep());

                for (int i = 1; i < JCBEstado.getItemCount(); i++) {
                    if (((Cad_Estado_TO) JCBEstado.getItemAt(i)).getId_cod_estado() == cad_fornecedor.getCad_estado().getId_cod_estado()) {
                        JCBEstado.setSelectedIndex(i);
                        break;
                    }
                }
                jtfCidade.setText(cad_fornecedor.getTxt_cidade());
                JDCDataCadastro.setDate(cad_fornecedor.getDt_datacadastro());
                JFTLTelefone.setText(cad_fornecedor.getNum_telefone());
                JFTLCelular1.setText(cad_fornecedor.getNum_celular1());
                JFTLCelular2.setText(cad_fornecedor.getNum_celular2());
                JTAObervacao.setText(cad_fornecedor.getTxt_observacao());
                BuscaFornecedor.dispose();

            }
        } catch (Throwable t) {
            JOptionPane.showMessageDialog(null, "Erro ao Carregar lista de Clientes!");
            limparDados();
            t.printStackTrace();
        }
    }//GEN-LAST:event_JBBuscaFornecedorActionPerformed

    private void JTFNomeRazaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNomeRazaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            carregaTabelaClientes();
            BuscaFornecedor.show();
        }
    }//GEN-LAST:event_JTFNomeRazaoKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame BuscaFornecedor;
    private javax.swing.JTable GradeBuscaFornecedor;
    private javax.swing.JButton JBBuscaFornecedor;
    private javax.swing.JButton JBCNPJCPF;
    private javax.swing.JButton JBGravar;
    private javax.swing.JLabel JBIncricaoEstadual;
    private javax.swing.JComboBox JCBEstado;
    private com.toedter.calendar.JDateChooser JDCDataCadastro;
    private javax.swing.JFormattedTextField JFTLCEP;
    private javax.swing.JFormattedTextField JFTLCelular1;
    private javax.swing.JFormattedTextField JFTLCelular2;
    private javax.swing.JFormattedTextField JFTLTelefone;
    private javax.swing.JLabel JLBairroDistrito;
    private javax.swing.JLabel JLCEP;
    private javax.swing.JLabel JLCPFCNPJ;
    private javax.swing.JLabel JLCelular1;
    private javax.swing.JLabel JLCelular2;
    private javax.swing.JLabel JLCidade;
    private javax.swing.JLabel JLDataCadastro;
    private javax.swing.JLabel JLEMAIL;
    private javax.swing.JLabel JLEndereco;
    private javax.swing.JLabel JLEstado;
    private javax.swing.JLabel JLNomeRazao;
    private javax.swing.JLabel JLNumero;
    private javax.swing.JLabel JLObservacao;
    private javax.swing.JLabel JLTelefone;
    private javax.swing.JEditorPane JTAObervacao;
    private javax.swing.JTextField JTFBairroDistrito;
    private javax.swing.JTextField JTFCPFCNPJ;
    private javax.swing.JTextField JTFEmail;
    private javax.swing.JTextField JTFEndereco;
    private javax.swing.JTextField JTFInscricaoEstadual;
    private javax.swing.JTextField JTFNomeRazao;
    private javax.swing.JTextField JTFNumero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtfCidade;
    // End of variables declaration//GEN-END:variables
}
